"""removed_category_id_from_event

Revision ID: 356bb0472e4b
Revises: 9e4fd8a69826
Create Date: 2025-05-04 11:18:43.504049

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '356bb0472e4b'
down_revision = '9e4fd8a69826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_category_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('event_category_id_fkey', 'event', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
