"""Add field user_id to uploadedfiles table

Revision ID: 409f43a89636
Revises: 3fbce20aa201
Create Date: 2025-05-08 15:55:47.139007

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '409f43a89636'
down_revision = '3fbce20aa201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadedfile', sa.Column('user_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadedfile', 'user_id')
    # ### end Alembic commands ###
