"""Add field full_name to message table

Revision ID: 840607e8fdcb
Revises: 409f43a89636
Create Date: 2025-05-09 13:47:13.019987

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '840607e8fdcb'
down_revision = '409f43a89636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'full_name')
    # ### end Alembic commands ###
