"""Add participant models

Revision ID: c542cb38d7ba
Revises: 0846657b45a8
Create Date: 2025-04-19 17:04:26.001649

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c542cb38d7ba'
down_revision = '0846657b45a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoryparticipant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.Enum('VIEW', 'EDIT', 'MANAGE', name='categorypermission'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventparticipant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('is_listener', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.Enum('VIEW', 'EDIT', 'ORGANIZE', name='eventpermission'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventparticipant')
    op.drop_table('categoryparticipant')
    # ### end Alembic commands ###
