"""user cal deletedd

Revision ID: cd04d61aa94a
Revises: 428829183075
Create Date: 2025-04-19 20:34:17.368392

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd04d61aa94a'
down_revision = '428829183075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
