"""test update mig

Revision ID: e8500d2d8458
Revises: cd04d61aa94a
Create Date: 2025-04-22 11:34:26.688575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e8500d2d8458'
down_revision = 'cd04d61aa94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
